# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    include:
      - python: 3.7
        dist: xenial
        sudo: true
        env: TOX_ENV=py37
      - python: 3.7
        dist: xenial
        sudo: true
        env: TOX_ENV=lint

install:
  - pip install tox
  - pip install .

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
